version: "3.8"

services:
  mysql:
    image: mysql:8.0.33
    container_name: trabalho03-mysql
    network_mode: "host"
    restart: no
    volumes:
      - trabalho03-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=trabalho03
      - MYSQL_USER=yuri
      - MYSQL_PASSWORD=nogueira
      - MYSQL_ROOT_PASSWORD=nogueira

volumes:
  trabalho03-mysql:
